[mypy]
python_version = 3.11
strict = True
warn_return_any = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
no_implicit_reexport = True
show_error_codes = True

[mypy-requests_mock.*]
ignore_missing_imports = True
